Syncing settings and assets
cloud-platforms-streaming/streaming-tools pull request #37
Opened 2021-02-17 20:23 UTC by chris-short

2021-02-17 20:24 UTC, chris-short commented
This PR is designed to take all the work done in the windows-vm branch and pushing it to master.

I'd like more eyeballs on this as the master branch is for Linux streamers.

2021-02-18 13:08 UTC, thoraxe requested changes
One minor change needed.

Is there not a way for all the scenes to start imported?

Also, how does this work across Linux, Mac, and Windows? Scene files have paths to assets and Windows paths don't look like Linux/Mac paths.

2021-02-18 13:08 UTC, thoraxe commented on obs/README.md
> +1. In OBS, select Scene Collection -> Import, use the path to the OBS scene `/opt/streaming-tools/obs/OpenShift_Streaming.json`, and click Add.
This file doesn't exist in this PR

2021-02-23 14:26 UTC, chris-short commented
This PR doesn't make sense at this time.

2021-02-23 14:26 UTC, closed without merging